import test,{type TestContext} from 'node:test';import assert from 'node:assert/strict';import {createActor} from 'xstate';import {createElement} from 'react';import {renderToStaticMarkup} from 'react-dom/server';
import {gameMachine} from '../src/state-machines/game-machine';import {CampaignSaveStore,SAVE_KEY,PREVIOUS_SAVE_KEY,campaignActorOptions,createCampaignPresentation} from '../src/persistence/campaignSave';import CharacterSelection from '../src/components/CharacterSelection';import CampaignSaveControls from '../src/components/CampaignSaveControls';import {startingCareerTitle} from '../src/lib/careerAccess';
for(const role of ['prince','minister','concubine'] as const)test(`${role}: selected role and narrative survive reload; choosing another path preserves backup`,t=>{
 t.mock.method(console,'log',()=>{});const data=new Map<string,string>(),storage={getItem:(k:string)=>data.get(k)??null,setItem:(k:string,v:string)=>{data.set(k,v)},removeItem:(k:string)=>{data.delete(k)}};const store=new CampaignSaveStore(storage);assert.equal(store.load().save,null);
 const game=createActor(gameMachine).start();t.after(()=>game.stop());game.send({type:'CHOOSE_CHARACTER',payload:{type:role}});game.send({type:'INITIALIZE_GAME'});assert.equal(game.getSnapshot().context.characterType,role);assert.ok(store.save(game,createCampaignPresentation(role)));const raw=data.get(SAVE_KEY)!;
 const again=new CampaignSaveStore(storage),save=again.load().save;assert.ok(save);const resumed=createActor(gameMachine,campaignActorOptions(save)).start();t.after(()=>resumed.stop());assert.equal(resumed.getSnapshot().context.characterType,role);assert.equal(JSON.stringify(resumed.getPersistedSnapshot()),JSON.stringify(game.getPersistedSnapshot()));
 const menu=renderToStaticMarkup(createElement(CampaignSaveControls,{store:again,onNewGame:()=>{},onRecover:()=>{},paused:true,onPauseChange:()=>{},role,rank:null,season:1}));assert.ok(menu.includes(`${startingCareerTitle(role)} · Season 1`));assert.match(menu,/Refresh resumes this campaign/);assert.match(menu,/Choose another path/);assert.match(menu,/<details class="save-details">/);
 assert.ok(again.startNewCampaign());assert.equal(data.get(SAVE_KEY),undefined);assert.equal(data.get(PREVIOUS_SAVE_KEY),raw);assert.equal(again.recoverPrevious()?.snapshot.context.characterType,role);
});
test('new-game screen always offers three distinct paths and role-specific origins',()=>{const html=renderToStaticMarkup(createElement(CharacterSelection,{onCharacterSelect:()=>{}}));for(const text of ['Play as The Prince','Play as The Scholar','Play as The Concubine','Born to power','Power through persuasion','A delicate ascent'])assert.ok(html.includes(text),text);assert.equal((html.match(/Born to power/g)||[]).length,1);});
