import test from 'node:test';import assert from 'node:assert/strict';
import {createCourtGraph,reduceCourtRelation,updateCourtNode,PLAYER_NODE,graphPledgedTo} from '../src/lib/courtGraph';
import {emptyCourtPlots,canPlot,canContinuePlot,safePlotInfluencePercent,cancelDefusedPlots,resolveCourtSeason,victimWeight,weightedVictim,type PlotSituation} from '../src/lib/courtPlots';
const people=['Prince Feng','Minister Chen','General Zhao','Maid Ling','Maid Su','Maid Bai'].map(name=>({name,formalFaction:'Independent' as const}));
function setup(allies=2):PlotSituation{let graph=createCourtGraph(people,123);for(const name of ['Prince Feng','Minister Chen','General Zhao'])graph=reduceCourtRelation(graph,name,PLAYER_NODE,{kind:'hate',amount:100},1).graph;for(const name of ['Maid Ling','Maid Su','Maid Bai'].slice(0,allies))graph=reduceCourtRelation(graph,name,PLAYER_NODE,{kind:'pledge'},1).graph;return{graph,role:'prince',rank:'grand_prince',playerInfluence:.5,influenceByName:{'Prince Feng':.7,'Minister Chen':.7,'General Zhao':.7,'Maid Ling':.1,'Maid Su':.1,'Maid Bai':.1}};}
test('middle+ strict influence/hate/faction/pledge eligibility; Emperor is never an ordinary plotter',()=>{const s=setup();assert.ok(canPlot(s,'Prince Feng'));assert.ok(!canPlot({...s,rank:null},'Prince Feng'));assert.ok(!canPlot({...s,playerInfluence:.7},'Prince Feng'));assert.ok(!canPlot(s,'Emperor'));let graph=updateCourtNode(updateCourtNode(s.graph,'Prince Feng',{faction:'Imperial'}),PLAYER_NODE,{faction:'Imperial'});assert.ok(!canPlot({...s,graph},'Prince Feng'));graph=structuredClone(s.graph);graph.edges['Prince Feng'][PLAYER_NODE].hate=79.99;assert.ok(!canPlot({...s,graph},'Prince Feng'));graph.edges['Prince Feng'][PLAYER_NODE].hate=80;assert.ok(canPlot({...s,graph},'Prince Feng'));});
test('new warnings grant a full season, attempts consume distinct allies, and unresolved plots strike again next season',()=>{
 let s=setup(3),state=resolveCourtSeason(s,emptyCourtPlots(),2,100);assert.equal(state.casualties.length,0);assert.equal(Object.keys(state.plots.pending).length,3);assert.ok(Object.values(state.plots.pending).every(p=>p.dueSeason===3));
 state=resolveCourtSeason({...s,graph:state.graph},state.plots,3,state.rngState);assert.equal(state.casualties.length,3);assert.equal(new Set(state.casualties.map(c=>c.name)).size,3);assert.equal(state.playerDeath,null);assert.equal(graphPledgedTo(state.graph,PLAYER_NODE).length,0);assert.equal(Object.keys(state.plots.pending).length,3);
 const repeat=resolveCourtSeason({...s,graph:state.graph},state.plots,3,state.rngState);assert.equal(repeat.casualties.length,0);assert.equal(repeat.rngState,state.rngState);
 state=resolveCourtSeason({...s,graph:state.graph},state.plots,4,state.rngState);assert.equal(state.playerDeath?.kind,'player_death');
});
test('three due attacks with two allies kills player only on third and never double-selects a victim',()=>{const s=setup(2),warn=resolveCourtSeason(s,emptyCourtPlots(),2,22),out=resolveCourtSeason(s,warn.plots,3,warn.rngState);assert.equal(out.casualties.length,2);assert.equal(new Set(out.casualties.map(c=>c.name)).size,2);assert.ok(out.playerDeath);assert.equal(out.graph.nodes[PLAYER_NODE].status,'deceased');});
test('out-influencing cancels a warning permanently without consuming RNG; a later threat needs a fresh full warning',()=>{const s=setup(),warn=resolveCourtSeason(s,emptyCourtPlots(),2,7),safe={...s,playerInfluence:.70000001};const canceled=cancelDefusedPlots(safe,warn.plots,2);assert.equal(Object.keys(canceled.pending).length,0);const fresh=resolveCourtSeason(s,canceled,3,warn.rngState);assert.equal(fresh.casualties.length,0);assert.ok(Object.values(fresh.plots.pending).every(p=>p.dueSeason===4));assert.equal(fresh.rngState,warn.rngState);});
test('victim weights use only attacker outgoing relationship, remain positive, and seeded save continuation is exact',()=>{const s=setup();let graph=structuredClone(s.graph);graph.edges['Prince Feng']['Maid Ling']={support:100,hate:0,pledge:null};graph.edges['Prince Feng']['Maid Su']={support:0,hate:100,pledge:null};assert.ok(victimWeight(graph,'Prince Feng','Maid Su',1)>victimWeight(graph,'Prince Feng','Maid Ling',1));const before=victimWeight(graph,'Prince Feng','Maid Ling',1);graph.edges['Maid Ling']['Prince Feng']={support:0,hate:100,pledge:null};assert.equal(victimWeight(graph,'Prince Feng','Maid Ling',1),before);assert.ok(before>0);assert.equal(weightedVictim(graph,'Prince Feng',['Maid Su','Maid Ling'],1,0),'Maid Ling');
 const warn=resolveCourtSeason({...s,graph},emptyCourtPlots(),2,765);const saved=JSON.parse(JSON.stringify(warn));assert.deepEqual(resolveCourtSeason({...s,graph:warn.graph},warn.plots,3,warn.rngState),resolveCourtSeason({...s,graph:saved.graph},saved.plots,3,saved.rngState));
});

test('equality sustains an active plot but never starts one; safe displayed target strictly beats exact influence',()=>{const s=setup(),warn=resolveCourtSeason(s,emptyCourtPlots(),2,7),equal={...s,playerInfluence:.7};assert.equal(canPlot(equal,'Prince Feng'),false);assert.equal(canContinuePlot(equal,'Prince Feng'),true);assert.equal(cancelDefusedPlots(equal,warn.plots,2),warn.plots);assert.equal(safePlotInfluencePercent(.8),'80.1');assert.equal(safePlotInfluencePercent(.80002),'80.1');assert.equal(safePlotInfluencePercent(.883),'88.4');});
import {deathMethodFor,DEATH_METHODS} from '../src/lib/courtPlots';
test('death-method variety is stable, persisted, and consumes no extra gameplay draw',()=>{const methods=new Set(Array.from({length:100},(_,n)=>deathMethodFor(24,n+1,'Prince Feng','Maid Ling')));assert.ok(methods.size>3);for(const method of methods)assert.ok(DEATH_METHODS.includes(method as any));const s=setup(3),warn=resolveCourtSeason(s,emptyCourtPlots(),2,80),result=resolveCourtSeason(s,warn.plots,3,warn.rngState);for(const death of result.casualties){assert.ok(death.deathMethod);assert.equal(result.plots.events.find(e=>e.victim===death.name)?.deathMethod,death.deathMethod);}const saved=JSON.parse(JSON.stringify(result));assert.deepEqual(saved.casualties,result.casualties);assert.equal(resolveCourtSeason({...s,graph:result.graph},saved.plots,3,saved.rngState).rngState,result.rngState);});
