import test,{beforeEach} from 'node:test';import assert from 'node:assert/strict';import {createActor} from 'xstate';import {createElement} from 'react';import {renderToStaticMarkup} from 'react-dom/server';import {readFileSync} from 'node:fs';
import {gameMachine} from '../src/state-machines/game-machine';import {captureCampaign,createCampaignPresentation,campaignActorOptions,parseCampaignSave} from '../src/persistence/campaignSave';import {emptyCourtPlots} from '../src/lib/courtPlots';import {createDemotionNotice} from '../src/lib/demotionNotice';import DemotionSummary from '../src/components/DemotionSummary';import SeasonTransition from '../src/palace/SeasonTransition';
beforeEach(t=>{t.mock.method(console,'log',()=>{});Object.defineProperty(globalThis,'alert',{configurable:true,value:()=>{}})});
for(const [role,from,to,deadline]of [['prince','grand_prince','prince',20],['prince','crown_prince','grand_prince',20],['minister','minister','scholar',16],['minister','prime_minister','minister',16],['concubine','consort','concubine',12],['concubine','empress','consort',12]] as const)test(`${from} demotion persists readable ${to} notice, survives reload and acknowledges once`,t=>{
 const machine=gameMachine.provide({guards:{emperor_encountered:()=>false,shouldOfferEmperorAudience:()=>false}}),g=createActor(machine).start();t.after(()=>g.stop());g.send({type:'CHOOSE_CHARACTER',payload:{type:role}});g.send({type:'INITIALIZE_GAME'});const raw:any=captureCampaign(g,createCampaignPresentation(role));raw.version=5;const c=raw.snapshot.context;Object.assign(c,{rank:from,season:deadline,rankEnteredSeason:1,supportPoints:0,courtPlots:emptyCourtPlots(deadline)});raw.presentation.clock.season=deadline;for(const ref of Object.values(c.characters) as any[])raw.snapshot.children[ref.id].snapshot.context.currentSeason=deadline;
 const r=createActor(machine,campaignActorOptions(parseCampaignSave(JSON.stringify(raw)).save)).start();t.after(()=>r.stop());r.send({type:'NEXT_SEASON'});const notice=r.getSnapshot().context.demotionNotice;assert.ok(notice);assert.equal(notice.fromRank,from);assert.equal(notice.toRank,to);assert.equal(notice.reason,'deadline');assert.equal(notice.acknowledged,false);assert.equal(notice.season,deadline+1);const saved=captureCampaign(r,createCampaignPresentation(role));assert.ok(saved);const rr=createActor(machine,campaignActorOptions(saved)).start();t.after(()=>rr.stop());assert.deepEqual(rr.getSnapshot().context.demotionNotice,notice);const before=rr.getSnapshot().context;rr.send({type:'ACKNOWLEDGE_DEMOTION',id:'stale'});assert.equal(rr.getSnapshot().context.demotionNotice?.acknowledged,false);rr.send({type:'ACKNOWLEDGE_DEMOTION',id:notice.id});assert.equal(rr.getSnapshot().context.demotionNotice?.acknowledged,true);assert.equal(rr.getSnapshot().context.giftsRemaining,before.giftsRemaining);assert.equal(rr.getSnapshot().context.season,before.season);assert.ok(captureCampaign(rr,createCampaignPresentation(role)));
 const html=renderToStaticMarkup(createElement(SeasonTransition,{season:notice.season,demotion:notice,giftGrant:20,castCount:14,faction:null,onComplete:()=>{}}));assert.match(html,/Demoted/);assert.match(html,/→/);assert.match(html,/rank deadline passed/);assert.match(html,/Continue when/);assert.doesNotMatch(html,/grand_prince|prime_minister/);
});
test('audience demotion titles and reason are distinct, and old saves have no fabricated notice',()=>{const n=createDemotionNotice('minister','prime_minister',9,'audience');assert.ok(n);const html=renderToStaticMarkup(createElement(DemotionSummary,{notice:n}));assert.match(html,/Prime Minister → Minister/);assert.match(html,/Emperor dismissed your audience/);assert.equal(createDemotionNotice('minister',null,1,'deadline'),null);assert.equal(createDemotionNotice('concubine','empress_consort',5,'deadline')?.fromRank,'empress');const source=readFileSync('src/state-machines/game-machine.ts','utf8');assert.equal((source.match(/createDemotionNotice\(context.characterType,context.rank,context.season,'audience'\)/g)||[]).length,2);});
test('demotion recaps do not auto-dismiss and saved unread notices drive a reload recap',()=>{const transition=readFileSync('src/palace/SeasonTransition.tsx','utf8');assert.ok(transition.indexOf('if(demotion)return')<transition.indexOf('const fade = setTimeout'));const ui=readFileSync('src/components/GameLayout.tsx','utf8');assert.match(ui,/recapSeason=transitionSeason\?\?\(demotion\?\.reason==='deadline'\?demotion.season:null\)/);assert.match(ui,/ACKNOWLEDGE_DEMOTION/);});

test('an audience demotion cannot be acknowledged by a hidden normal season recap timer',()=>{const ui=readFileSync('src/components/GameLayout.tsx','utf8');assert.match(ui,/recapSeason!==null && demotion\?\.reason!=='audience' && <SeasonTransition/);assert.match(ui,/onComplete=\{\(\)=>\{if\(demotion\?\.reason==='deadline'\)acknowledgeDemotion\(\);setTransitionSeason\(null\);\}\}/);});
