import {tributeCost} from '../src/lib/campaignBalance';
import {nextCampaignRandom} from '../src/lib/campaignRandom';
import test,{beforeEach,type TestContext} from 'node:test';
import assert from 'node:assert/strict';
import {createActor,fromPromise,waitFor} from 'xstate';
import {gameMachine} from '../src/state-machines/game-machine';
import {emperorAudienceMachine} from '../src/state-machines/emperor-audience-machine';
import {FALLBACK_QUESTIONS} from '../src/data/fallbackQuestions';
import {CAMPAIGN_BALANCE as B,rankIndex,seasonalGiftGrant} from '../src/lib/campaignBalance';
import {getSupportThreshold} from '../src/lib/helpers';
import {assignCharacterFaction,checkFactionMembershipOffers} from '../src/lib/factionSystem';
import {determineVictoryPath} from '../src/lib/emperorAudience';
import {witnessedRebelGift} from '../src/lib/courtIntrigue';
import type {PlayerType} from '../src/types/game';
beforeEach(t=>{t.mock.method(Math,'random',()=>.99);t.mock.method(console,'log',()=>{});Object.defineProperty(globalThis,'alert',{configurable:true,value:()=>{}});t.mock.method(globalThis,'fetch',async()=>{throw Error('No external calls in campaign tests');});});
function start(t:TestContext,role:PlayerType='prince',machine=gameMachine.provide({guards:{emperor_encountered:()=>false}})){const game=createActor(machine);const errors:unknown[]=[];game.subscribe({error:e=>errors.push(e)});game.start();game.send({type:'CHOOSE_CHARACTER',payload:{type:role}});game.send({type:'INITIALIZE_GAME'});t.after(()=>{game.stop();assert.deepEqual(errors,[]);});return game;}
function award(game:ReturnType<typeof start>,name:string,amount=100){const actor=game.getSnapshot().context.characters[name];actor.send({type:'ACTIVATE'});actor.send({type:'APPLY_FACTION_BONUS',supportBonus:amount,trustBonus:0});return actor;}
function topRank(game:ReturnType<typeof start>){for(const name of ['Empress Dowager','Empress Consort','Crown Prince','Prime Minister'])if(game.getSnapshot().context.characters[name])award(game,name);assert.equal(rankIndex(game.getSnapshot().context.characterType,game.getSnapshot().context.rank),2);}
const drain=async()=>{for(let i=0;i<15;i++)await Promise.resolve();};
for(const role of ['prince','minister','concubine'] as PlayerType[]){
 test(`${role}: initializes48 persistent actors, unique seasonal cast and configured backing`,t=>{const g=start(t,role),c=g.getSnapshot().context;assert.equal(c.giftsRemaining,seasonalGiftGrant(role,null));assert.equal(Object.keys(c.characters).length,48);assert.equal(new Set(c.activeCharacterNames).size,c.activeCharacterNames.length);for(const a of Object.values(c.characters))assert.equal(a.getSnapshot().context.supportThreshold,getSupportThreshold(role));});
 test(`${role}: progression has two promotions, expels the displaced office holder and has no generic points victory`,t=>{const g=start(t,role);const actors={...g.getSnapshot().context.characters};topRank(g);const c=g.getSnapshot().context;assert.ok(c.supportPoints>100);assert.notEqual(g.getSnapshot().value,'game_over');assert.equal(Object.keys(c.characters).length,47);for(const [name,a]of Object.entries(actors)){if(c.expelledCourtiers[name])assert.equal(a.getSnapshot().status,'stopped');else assert.equal(c.characters[name],a);}assert.equal(c.rewardedRanks.length,2);assert.equal(c.rankEnteredSeason,1);});
 test(`${role}: bottom deadline gives the career-specific loss only after full window`,t=>{const g=start(t,role);const window=role==='prince'?20:role==='minister'?16:12;for(let i=1;i<window;i++)g.send({type:'NEXT_SEASON'});assert.equal(g.getSnapshot().context.season,window);assert.notEqual(g.getSnapshot().value,'game_over');g.send({type:'NEXT_SEASON'});assert.equal(g.getSnapshot().value,'game_over');assert.match(g.getSnapshot().context.careerEnding!.description,role==='prince'?/lord/:role==='minister'?/peasant/:/maid/);});
 test(`${role}: top deadline demotes exactly one rank with fresh window and nonfarmable probation`,t=>{const g=start(t,role);topRank(g);const influence=g.getSnapshot().context.playerPersonality.influence;const window=role==='prince'?20:role==='minister'?16:12;for(let i=0;i<window;i++)g.send({type:'NEXT_SEASON'});const c=g.getSnapshot().context;assert.equal(rankIndex(role,c.rank),1);assert.equal(c.rankEnteredSeason,window+1);assert.equal(c.promotionEligibleAfterSeason,window+3);assert.equal(c.playerPersonality.influence,influence-B.demotionInfluenceLoss);const oldInfluence=c.playerPersonality.influence;g.send({type:'NEXT_SEASON'});assert.equal(rankIndex(role,g.getSnapshot().context.rank),1);g.send({type:'NEXT_SEASON'});assert.equal(rankIndex(role,g.getSnapshot().context.rank),1,'reset standing must be rebuilt; probation alone cannot restore office');assert.equal(g.getSnapshot().context.playerPersonality.influence,oldInfluence,'no second promotion bonus farming');});
}
test('standing reports are backed by real milestones, uncapped and idempotent',t=>{const g=start(t);g.send({type:'CHARACTER_GAVE_SUPPORT',name:'Fake',characterType:'major'});assert.equal(g.getSnapshot().context.supportPoints,0);const a=award(g,'Crown Prince');const points=g.getSnapshot().context.supportPoints;g.send({type:'CHARACTER_GAVE_SUPPORT',name:'Crown Prince',characterType:'major'});g.send({type:'CHARACTER_GAVE_ALLEGIANCE',name:'Crown Prince',characterType:'major'});assert.equal(g.getSnapshot().context.supportPoints,points);a.send({type:'DEACTIVATE'});a.send({type:'ACTIVATE'});assert.equal(g.getSnapshot().context.supportPoints,points);});
test('current backing withdraws on hostility even for inactive actors; pledges are exempt',t=>{const g=start(t,'concubine'),c=g.getSnapshot().context;const a=c.characters['Concubine Mei'];a.send({type:'ACTIVATE'});a.send({type:'APPLY_FACTION_BONUS',supportBonus:80,trustBonus:0});a.send({type:'DEACTIVATE'});a.send({type:'CONSORT_HOSTILITY'});assert.equal(a.getSnapshot().context.supportLevel,79);assert.equal(a.getSnapshot().context.hate,40);const ally=award(g,'Maid Ling');ally.send({type:'DEACTIVATE'});ally.send({type:'CONSORT_HOSTILITY'});ally.send({type:'APPLY_SUSPICION_CHANGE',suspicionChange:.99});assert.equal(ally.getSnapshot().context.hate,0);assert.equal(ally.getSnapshot().context.suspicion,0);});
test('Consort ceremony targets actual Empress faction once and preserves NPC identities',t=>{const g=start(t,'concubine'),c=g.getSnapshot().context;const empress=c.characters['Empress Consort'];award(g,'Maid Ling');award(g,'Maid Su');award(g,'Maid Bai');award(g,'Maid Lan');award(g,'Empress Dowager');assert.equal(g.getSnapshot().context.rank,'consort');assert.equal(empress.getSnapshot().context.hate,40);assert.equal(g.getSnapshot().context.consortBacklashApplied,true);assert.equal(g.getSnapshot().context.characters['Empress Consort'],empress);assert.equal(c.characters['Maid Ling'].getSnapshot().context.hate,0);});
test('pledged inactive allies follow a legitimate faction join and stay immune through seasons',t=>{const g=start(t,'prince');for(const name of ['Maid Ling','Maid Su','Maid Bai'])award(g,name);const ally=g.getSnapshot().context.characters['Maid Ling'];ally.send({type:'DEACTIVATE'});const faction=assignCharacterFaction({...ally.getSnapshot().context,type:'minor'});assert.ok(checkFactionMembershipOffers(g.getSnapshot().context.factionSystem,g.getSnapshot().context.characters).includes(faction));g.send({type:'JOIN_FACTION',faction});assert.equal(g.getSnapshot().context.factionSystem.playerFaction,faction);assert.equal(ally.getSnapshot().context.factionOverride,faction);for(let i=0;i<4;i++){g.send({type:'NEXT_SEASON'});ally.send({type:'APPLY_SUSPICION_CHANGE',suspicionChange:1});}assert.equal(ally.getSnapshot().context.suspicion,0);});
test('stale or fabricated faction invitation cannot be joined',t=>{const g=start(t);g.send({type:'FACTION_MEMBERSHIP_OFFERED',faction:'Rebel'});g.send({type:'JOIN_FACTION',faction:'Rebel'});assert.equal(g.getSnapshot().context.factionSystem.playerFaction,null);});
test('witness snapshot restricts rebel suspicion by zone, faction, pledge and hatred',()=>{const witnesses=[{name:'Local',faction:'Imperial',pledged:false,hate:0,zone:'ladies'},{name:'Enemy',faction:'Loyalist',pledged:false,hate:80,zone:'ladies'},{name:'Ally',faction:'Imperial',pledged:true,hate:80,zone:'ladies'},{name:'Distant',faction:'Imperial',pledged:false,hate:80,zone:'library'}] as const;const effects=witnessedRebelGift('ambitious','Rebel','Recipient','ladies',witnesses);assert.deepEqual(effects.map(x=>x.characterName),['Local','Enemy']);assert.equal(effects[0].suspicionChange,.1);assert.ok(Math.abs(effects[1].suspicionChange-.15)<1e-9);assert.equal(witnessedRebelGift('loyal','Rebel','Recipient','ladies',witnesses).length,0);assert.equal(witnessedRebelGift('ambitious','Independent','Recipient','ladies',witnesses).length,0);});
for(const event of ['NEXT_SEASON','SEASON_EXPIRED'] as const)test(`${event}: tribute commits exactly one season, one charge and one favor roll`,t=>{const g=start(t,'prince',gameMachine.provide({guards:{emperor_encountered:({context})=>context.season>=2}}));g.send({type:'NEXT_SEASON'});const gifts=g.getSnapshot().context.giftsRemaining;g.send({type:event});assert.ok(g.getSnapshot().matches({playing:'emperor_encounter'}));const influence=g.getSnapshot().context.playerPersonality.influence;const favored=nextCampaignRandom(g.getSnapshot().context.rngState).value<B.tributeFavorChance;g.send({type:'GIVE_EMPEROR_GIFT',giftsRemaining:999});const after=g.getSnapshot().context;assert.equal(after.season,3);assert.equal(after.giftsRemaining,gifts-tributeCost('prince',null)+seasonalGiftGrant('prince',null));assert.ok(Math.abs(after.playerPersonality.influence-influence-(favored?B.tributeInfluenceReward:0))<1e-9);g.send({type:'GIVE_EMPEROR_GIFT',giftsRemaining:999});assert.equal(g.getSnapshot().context.season,3);assert.equal(g.getSnapshot().context.giftsRemaining,after.giftsRemaining);});
for(const [faction,path]of [['Imperial','traditional'],['Loyalist','shadow-ruler'],['Rebel','revolutionary']] as const)test(`${faction}: only top office unlocks existing faction ending`,()=>{const base:any={characterType:'prince',rank:'grand_prince',season:4,rankEnteredSeason:1,factionSystem:{playerFaction:faction}};assert.equal(determineVictoryPath(base),null);assert.equal(determineVictoryPath({...base,rank:'crown_prince'}),path);assert.equal(determineVictoryPath({...base,rank:'crown_prince',factionSystem:{playerFaction:null}}),null);});
test('actual successful faction audience reaches victory, restart stops old actors and resets career',async t=>{const machine=gameMachine.provide({guards:{emperor_encountered:()=>false},actors:{emperorAudienceMachine:emperorAudienceMachine.provide({actors:{generateQuestionsActor:fromPromise(async({input}:any)=>({questions:FALLBACK_QUESTIONS[input.path as keyof typeof FALLBACK_QUESTIONS]})),judgeOutcomeActor:fromPromise(async()=>({outcome:'victory' as const,message:'Test faction victory'}))}})}});const g=start(t,'prince',machine);for(const n of ['Maid Ling','Maid Su','Maid Bai'])award(g,n);g.send({type:'JOIN_FACTION',faction:'Loyalist'});topRank(g);for(let i=0;i<3;i++){assert.notEqual(g.getSnapshot().value,'emperor_audience_offer');g.send({type:'NEXT_SEASON'});}assert.equal(g.getSnapshot().value,'emperor_audience_offer');g.send({type:'ENTER_AUDIENCE'});await drain();const audience=g.getSnapshot().children.emperorAudienceMachine as any;for(let i=0;i<3;i++)audience.send({type:'ANSWER_QUESTION',answer:'a'});await waitFor(g,s=>s.value==='game_over');assert.equal(g.getSnapshot().context.gameEndReason,'victory');const actors=Object.values(g.getSnapshot().context.characters);g.send({type:'RESTART_GAME'});assert.equal(g.getSnapshot().value,'choosing_character');assert.equal(g.getSnapshot().context.supportPoints,0);assert.equal(g.getSnapshot().context.standingAwards.length,0);assert.equal(g.getSnapshot().context.consortBacklashApplied,false);for(const a of actors)assert.equal(a.getSnapshot().status,'stopped');});
test('hostile action validation rejects unknown, absent and protected targets without crashing',t=>{const g=start(t),c=g.getSnapshot().context;const major=c.activeCharacterNames.find(n=>c.characters[n].getSnapshot().context.type==='major')!;const a=c.characters[major],before=structuredClone(a.getSnapshot().context);g.send({type:'SPIT_IN_FACE',characterId:'Unknown'});g.send({type:'SPIT_IN_FACE',characterId:major});assert.deepEqual(a.getSnapshot().context,before);const target=c.activeCharacterNames.find(n=>c.characters[n].getSnapshot().context.personalityVectors.influence<=.6)!;if(target){g.send({type:'UPDATE_PALACE_PRESENCE',zone:'library',names:[]});const old=c.characters[target].getSnapshot().context.suspicion;g.send({type:'SPIT_IN_FACE',characterId:target});assert.equal(c.characters[target].getSnapshot().context.suspicion,old);}});
test('top office expels its NPC permanently from active cast and faction contributors, including after demotion',t=>{const g=start(t,'prince'),crown=g.getSnapshot().context.characters['Crown Prince'];topRank(g);assert.ok(g.getSnapshot().context.expelledCourtiers['Crown Prince']);assert.equal(g.getSnapshot().context.characters['Crown Prince'],undefined);assert.equal(crown.getSnapshot().status,'stopped');assert.ok(!g.getSnapshot().context.activeCharacterNames.includes('Crown Prince'));for(let i=0;i<20;i++)g.send({type:'NEXT_SEASON'});assert.equal(g.getSnapshot().context.rank,'grand_prince');assert.equal(g.getSnapshot().context.characters['Crown Prince'],undefined);assert.ok(g.getSnapshot().context.expelledCourtiers['Crown Prince']);});
test('first Consort promotion excludes Dowager; later earned influence milestones do affect her',t=>{
 const g=start(t,'concubine'),c=g.getSnapshot().context,dowager=c.characters['Empress Dowager'],empress=c.characters['Empress Consort'];
 award(g,'Crown Prince');assert.equal(g.getSnapshot().context.rank,'consort');assert.equal(empress.getSnapshot().context.hate,40);assert.equal(dowager.getSnapshot().context.hate,0);
 award(g,'Prime Minister',80);assert.equal(empress.getSnapshot().context.hate,45);assert.equal(dowager.getSnapshot().context.hate,5);
});
test('a retained maxed ally can rebuild reset global standing through a paid evaluated gift, once per season',async t=>{
 const g=start(t,'concubine');topRank(g);for(let i=0;i<12;i++)g.send({type:'NEXT_SEASON'});
 const c=g.getSnapshot().context;assert.equal(c.rank,'consort');assert.equal(c.supportPoints,B.roles.concubine.globalTargets[0]);
 const name='Empress Dowager',ally=c.characters[name];assert.equal(ally.getSnapshot().context.supportLevel,100);
 assert.ok(c.activeCharacterNames.includes(name));g.send({type:'UPDATE_PALACE_PRESENCE',zone:'dowager',names:[name]});
 const gifts=c.giftsRemaining;
 g.send({type:'GIVE_GIFT_WITH_MESSAGE',characterId:name,messageType:'loyal',requestId:'renewal-one'});await drain();
 const first=g.getSnapshot().context;assert.equal(first.lastGiftReceipt?.globalRenewal,12.5);assert.equal(first.supportPoints,c.supportPoints+12.5);assert.equal(first.giftsRemaining,gifts-20);assert.equal(ally.getSnapshot().context.supportLevel,100);
 g.send({type:'GIVE_GIFT_WITH_MESSAGE',characterId:name,messageType:'loyal',requestId:'renewal-one'});await drain();assert.equal(g.getSnapshot().context.giftsRemaining,gifts-20);
 g.send({type:'GIVE_GIFT_WITH_MESSAGE',characterId:name,messageType:'loyal',requestId:'renewal-two'});await drain();assert.equal(g.getSnapshot().context.lastGiftReceipt?.globalRenewal,0);assert.equal(g.getSnapshot().context.supportPoints,first.supportPoints);assert.equal(g.getSnapshot().context.giftsRemaining,gifts-40);
 g.send({type:'NEXT_SEASON'});g.send({type:'UPDATE_PALACE_PRESENCE',zone:'dowager',names:[name]});g.send({type:'GIVE_GIFT_WITH_MESSAGE',characterId:name,messageType:'loyal',requestId:'renewal-next-season'});await drain();assert.equal(g.getSnapshot().context.supportPoints,first.supportPoints+12.5);
});
